name: Deploy to Windows

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: windows-latest  # Using the latest Windows runner for the job
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI for Windows
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update to your AWS region

      # Step 3: Deploy to Windows server using PowerShell or SSH
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your SSH key in GitHub secrets
          EC2_USER: ubuntu  # Change if your EC2 instance uses a different user (e.g., 'ec2-user' for Amazon Linux)
          EC2_HOST: ${{ secrets.EC2_HOST }}  # The public IP or DNS of your EC2 instance
        run: |
          # Add SSH key to the SSH agent (For Windows, this may use OpenSSH)
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # SSH into EC2 and deploy the application (Windows version of SSH command)
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /path/to/your/project  # Go to the project directory on the EC2 instance
            git pull origin main  # Pull the latest code
            npm install  # Install dependencies (adjust if using another package manager)
            pm2 restart app  # Restart the app (adjust for your environment)
          EOF

